
import java.awt.Color;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Boukhtache Younes  <Boukhtache at gmail.com>
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
     int x,y;
    private ImageIcon format = null;
    Calendar timer=Calendar.getInstance();
    SimpleDateFormat tim=new SimpleDateFormat("yyyy-MM-dd");
   LockClock lk=new LockClock("Clock");
    public Home() {
        initComponents();
        getDateDay();
        ClockStart();
      // setBG(jbg,"/bg0.png");
       setPic(jbg,"/bg0.png");
       icons();
       setBackground(new Color(240,240,240,Color.TRANSLUCENT));
       lk.appClosable();
    }
    private void icons(){
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/clock.png")));
      } 
    public void getDateDay(){
        Date dt=new Date(); timer.setTime(dt);
         String dtm=tim.format(timer.getTime());
         jdate.setText(dtm);
    }
    public void setPic(JLabel lbl,String image){
        ImageIcon img = new ImageIcon(getClass().getResource(image));
        lbl.setIcon(img);
    }
//public void setBG(JLabel lbl,String image){
//      format = new ImageIcon(new ImageIcon(getClass().getResource(image)).getImage()
//       .getScaledInstance(lbl.getWidth(),lbl.getHeight(), Image.SCALE_SMOOTH));
//                lbl.setIcon(format);
//  }
  public void ClockStart(){
	Thread tm=new Thread(){
	public void run(){
	try {  //while(true)
		for(;;){
		Calendar cal=new GregorianCalendar();
		int hour=cal.get(Calendar.HOUR_OF_DAY);
		int minute=cal.get(Calendar.MINUTE);
		int second=cal.get(Calendar.SECOND);
//           if(hour>=12){
//           setBG(jhour,"/Hour/h"+(hour-12)+".png"); 
//        }else{
//           setBG(jhour,"/Hour/h"+hour+".png");  
//        }     
        //  setBG(jseconde,"/Second/s"+second+".png");
        //  setBG(jminute,"/Minute/m"+minute+".png"); 
           setPic(jseconde,"/Second/s"+second+".png");
           setPic(jminute,"/Minute/m"+minute+".png");
//        if(hour>=12){
//           setPic(jhour,"/Hour/h"+(hour-12)+".png"); 
//        }else if(minute>30){
//           setPic(jhour,"/Hour/h"+hour+"_1.png");  
//        }else if(hour>=12 && minute>30){
//           setPic(jhour,"/Hour/h"+(hour-12)+"_1.png");  
//        }else{
//           setPic(jhour,"/Hour/h"+hour+".png");  
//        }

 if(minute>30){
setPic(jhour,"/Hour/h"+hour+"_1.png");
}else if(minute<=30){
setPic(jhour,"/Hour/h"+hour+".png");
}
           sleep(1000);
		}
	} catch (InterruptedException e) {
		e.printStackTrace(); }
	        	 }
		};
		tm.start();
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jexit = new javax.swing.JLabel();
        jseconde = new javax.swing.JLabel();
        jminute = new javax.swing.JLabel();
        jhour = new javax.swing.JLabel();
        jlogo = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        jbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jexit.setBackground(new java.awt.Color(0, 0, 0));
        jexit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jexit.setForeground(new java.awt.Color(255, 255, 255));
        jexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jexit.setText("x");
        jexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexit.setOpaque(true);
        jexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jexitMouseExited(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, -1));

        jseconde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jseconde.setPreferredSize(new java.awt.Dimension(240, 200));
        getContentPane().add(jseconde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 200));

        jminute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jminute.setPreferredSize(new java.awt.Dimension(240, 200));
        getContentPane().add(jminute, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 200));

        jhour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhour.setPreferredSize(new java.awt.Dimension(240, 200));
        getContentPane().add(jhour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 200));

        jlogo.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jlogo.setForeground(new java.awt.Color(255, 255, 255));
        jlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlogo.setText("BOUKHTACHE/YOUNES");
        getContentPane().add(jlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 110, 100, 20));

        jdate.setBackground(new java.awt.Color(0, 0, 0));
        jdate.setForeground(new java.awt.Color(255, 255, 255));
        jdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 70, 20));

        jbg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbg.setPreferredSize(new java.awt.Dimension(240, 200));
        jbg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbgMouseDragged(evt);
            }
        });
        jbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbgMouseReleased(evt);
            }
        });
        getContentPane().add(jbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jexitMouseClicked

    private void jexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseEntered
       jexit.setBackground(new Color(191, 0, 0));
    }//GEN-LAST:event_jexitMouseEntered

    private void jexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseExited
        jexit.setBackground(new Color(1,1,1));
    }//GEN-LAST:event_jexitMouseExited

    private void jbgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbgMouseDragged
         int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jbgMouseDragged

    private void jbgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbgMousePressed
         x = evt.getX();
        y = evt.getY();
        setOpacity((float) 0.7);
    }//GEN-LAST:event_jbgMousePressed

    private void jbgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbgMouseReleased
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jbgMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jbg;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jexit;
    private javax.swing.JLabel jhour;
    private javax.swing.JLabel jlogo;
    private javax.swing.JLabel jminute;
    private javax.swing.JLabel jseconde;
    // End of variables declaration//GEN-END:variables
}
